stages:
  network:
    cmd: make input/before-calibration/output/dresden-v1.1-network-with-pt.xml.gz
    deps:
      - input/sumo
      - input/osm
      - input/shp
    outs:
      - input/before-calibration/output/dresden-v1.1-network-with-pt.xml.gz
  population:
    cmd: make prepare
    deps:
      - input/20250123_Teilmodell_Hoyerswerda
      - input/sumo
      - input/osm
      - input/landuse
      - input/20250130_Teilmodell_Hoyerswerda
      - input/shp
      - input/gtfs
      - input/germanWideFreight
      - input/before-calibration/output/dresden-v1.1-network-with-pt.xml.gz

    outs:
      - input/before-calibration/output/dresden-v1.1-100pct.plans-initial.xml.gz
