stages:
  network:
    cmd: make input/before-calibration/output/dresden-v1.1-network-with-pt.xml.gz
    deps:
      - Makefile
      - input/sumo
      - input/osm
      - input/shp
      - input/gtfs
    outs:
      - input/before-calibration/output/dresden-v1.1-network-with-pt.xml.gz
      - input/before-calibration/output/dresden-v1.1-transitSchedule.xml.gz
      - input/before-calibration/output/dresden-v1.1-transitVehicles.xml.gz
  persons:
    cmd: make input/before-calibration/output/prepare-100pct-persons.xml.gz
    deps:
      - Makefile
      - input/20250123_Teilmodell_Hoyerswerda
      - input/sumo
      - input/osm
      - input/landuse
      - input/20250130_Teilmodell_Hoyerswerda
      - input/shp
      - input/gtfs
      - input/germanWideFreight
      - input/before-calibration/output/dresden-v1.1-network-with-pt.xml.gz
    outs:
      - input/before-calibration/output/prepare-100pct-persons.xml.gz
  population:
    cmd: make prepare
    deps:
      - Makefile
      - input/20250123_Teilmodell_Hoyerswerda
      - input/sumo
      - input/osm
      - input/landuse
      - input/20250130_Teilmodell_Hoyerswerda
      - input/shp
      - input/gtfs
      - input/germanWideFreight
      - input/before-calibration/output/dresden-v1.1-network-with-pt.xml.gz
      - input/before-calibration/output/prepare-100pct-persons.xml.gz
    outs:
      - input/before-calibration/output/dresden-v1.1-100pct.plans-initial.xml.gz
      - input/before-calibration/output/dresden-v1.1-10pct.plans-initial.xml.gz
      - input/before-calibration/output/dresden-v1.1-1pct.plans-initial.xml.gz
      - input/before-calibration/output/dresden-v1.1-0pct.plans-initial.xml.gz
      - input/before-calibration/output/dresden-v1.1-activity-facilities.xml.gz
  run:
    cmd: make run-1pct
