stages:
  prepare:
    cmd: make prepare
    deps:
      - input/20250123_Teilmodell_Hoyerswerda.dvc
      - input/sumo.dvc
      - input/osm.dvc
      - input/landuse.dvc
      - input/20250130_Teilmodell_Hoyerswerda.dvc
      - input/shp.dvc
      - input/gtfs.dvc
      - input/germanWideFreight.dvc
    outs:
      - input/before-calibration
