name: build
on: push
jobs:
  build:
    # push, or pull_request from fork
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 25
          architecture: x64
          distribution: adopt
          cache: maven
      - run: mvn --batch-mode --update-snapshots package checkstyle:checkstyle enforcer:enforce -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
      - run: mkdir staging && cp *.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
    env:
      MAVEN_OPTS: -Xmx512m